using System;
using System.Collections.Generic;

namespace TheCoreBanking.Authenticate.Data.Model
{
    public partial class TblBankingLoanLease
    {
        public int Id { get; set; }
        public string CustName { get; set; }
        public string CustCode { get; set; }
        public string ProductCode { get; set; }
        public string ProductName { get; set; }
        public string ProductAcctNo { get; set; }
        public string BranchId { get; set; }
        public int? Tenor { get; set; }
        public decimal? Rate { get; set; }
        public int? Moratorium { get; set; }
        public int? Installments { get; set; }
        public DateTime? EffectDate { get; set; }
        public DateTime? TerminalDate { get; set; }
        public string CoyCode { get; set; }
        public string Miscode { get; set; }
        public DateTime? DateCreated { get; set; }
        public decimal? Principal { get; set; }
        public decimal? LastprincipalPaid { get; set; }
        public int? InstalmentLeft { get; set; }
        public bool? Approved { get; set; }
        public string ApprovedBy { get; set; }
        public DateTime? DateApproved { get; set; }
        public int? Status { get; set; }
        public string CurrentAcct { get; set; }
        public bool? Disapprove { get; set; }
        public decimal? LastInterestPaid { get; set; }
        public int? OperationId { get; set; }
        public string Sbumis { get; set; }
        public string Officer1 { get; set; }
        public string Officer2 { get; set; }
        public bool? Disbursed { get; set; }
        public string Disburser { get; set; }
        public DateTime? DateOfDisburse { get; set; }
        public string DisburseComment { get; set; }
        public string OpeningComment { get; set; }
        public string ApprovalComment { get; set; }
        public string ApproveOpComment { get; set; }
        public string ApproveMaintainComment { get; set; }
        public bool? Email { get; set; }
        public bool? Sms { get; set; }
        public bool? InternetBanking { get; set; }
        public int? SchMethod { get; set; }
        public bool? Lien { get; set; }
        public int? GroupNo { get; set; }
        public string GroupId { get; set; }
        public bool? Riskass { get; set; }
        public decimal? Frequency { get; set; }
        public int? BulletType { get; set; }
        public int? BulletFreq { get; set; }
        public string FreqType { get; set; }
        public string BulletName { get; set; }
        public string BulletFreqName { get; set; }
        public bool? Legals { get; set; }
        public bool? Cam { get; set; }
        public bool? OfferLetter { get; set; }
        public decimal? TargetAmount { get; set; }
        public string Ref { get; set; }
        public bool? ProfileLoan { get; set; }
        public int? TenorMode { get; set; }
        public bool? MoraWinthInterest { get; set; }
        public bool? DisChargeLetter { get; set; }
        public bool? TempCam { get; set; }
        public bool? TempRisk { get; set; }
        public bool? RiskReceived { get; set; }
        public bool? LegalReceived { get; set; }
        public decimal? InterestAmount { get; set; }
        public decimal? MaturityAmount { get; set; }
        public string Upload { get; set; }
        public decimal? SchPayment { get; set; }
        public int? CategoryId { get; set; }
        public int? PdTypeId { get; set; }
        public bool? Paid { get; set; }
        public decimal? AmountPaid { get; set; }
        public string Currency { get; set; }
        public decimal? PeriodicPay { get; set; }
        public DateTime? DatePaid { get; set; }
        public bool? Nhf { get; set; }
        public string CreditMandate { get; set; }
        public bool? AgreeLoan { get; set; }
        public bool? SetOff { get; set; }
        public decimal? CurrRate { get; set; }
        public decimal? FeePercent { get; set; }
        public int? FeeFrequency { get; set; }
        public DateTime? FirstpayDate { get; set; }
        public bool? SetEqualDate { get; set; }
        public string ApprovalType { get; set; }
        public decimal? OutstandingPrincipal { get; set; }
        public int? NoOfPrincipalAddition { get; set; }
        public int? NoOfPrincipalReduction { get; set; }
        public bool? SuspendInterest { get; set; }
        public bool? CanDisburse { get; set; }
        public string Pccode1 { get; set; }
        public string Pccode2 { get; set; }
        public bool? Booked { get; set; }
        public bool? Scheduled { get; set; }
        public decimal? ApprovedAmount { get; set; }
        public decimal? PrincipalFrequency { get; set; }
        public string PrincipalFreqType { get; set; }
        public decimal? FixedPrincipal { get; set; }
        public string CreatedBy { get; set; }
        public decimal? UpfrontInterest { get; set; }
        public decimal? Upfrontprincipal { get; set; }
        public int? Upfrontmonths { get; set; }
        public bool? IssueOfferletter { get; set; }
        public string MyPath { get; set; }
        public string RelationshipManager { get; set; }
        public string RelationshipManagerDept { get; set; }
        public string RelationshipOfficer { get; set; }
        public string RelationshipOfficerDept { get; set; }
    }
}
